### ISSUE TITLE
android.content.res.Resources$NotFoundException: File res/drawable-xxxhdpi-v4/ic_spotlight_arc.png

### ISSUE THREAD

**Issue by ThinkingMonkey** [wooplr/Spotlight#1]
Hi,
First of all a great lib for show casing the app. Very nice UI. Have started using it in an application.

Works great on Android 5. 

Facing issues on android 4.4.2 :

```java

android.content.res.Resources$NotFoundException: File res/drawable-xxxhdpi-v4/ic_spotlight_arc.png from xml type xml resource ID #0x7f0200d0
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2396)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2351)
	at android.content.res.Resources.getXml(Resources.java:1028)
	at android.content.res.XResources.getXml(XResources.java:745)
	at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:408)
	at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:356)
	at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:162)
	at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:142)
	at com.wooplr.spotlight.SpotlightView.addArcAnimation(SpotlightView.java:521)
	at com.wooplr.spotlight.SpotlightView.access$300(SpotlightView.java:50)
	at com.wooplr.spotlight.SpotlightView$4.onAnimationEnd(SpotlightView.java:433)
	at android.view.animation.Animation$3.run(Animation.java:374)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5118)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.FileNotFoundException: Corrupt XML binary file
	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:495)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2378)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2351) 
	at android.content.res.Resources.getXml(Resources.java:1028) 
	at android.content.res.XResources.getXml(XResources.java:745) 
	at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:408) 
	at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:356) 
	at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:162) 
	at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:142) 
	at com.wooplr.spotlight.SpotlightView.addArcAnimation(SpotlightView.java:521) 
	at com.wooplr.spotlight.SpotlightView.access$300(SpotlightView.java:50) 
	at com.wooplr.spotlight.SpotlightView$4.onAnimationEnd(SpotlightView.java:433) 
	at android.view.animation.Animation$3.run(Animation.java:374) 
	at android.os.Handler.handleCallback(Handler.java:733) 
	at android.os.Handler.dispatchMessage(Handler.java:95) 
	at android.os.Looper.loop(Looper.java:136) 
	at android.app.ActivityThread.main(ActivityThread.java:5118) 
	at java.lang.reflect.Method.invokeNative(Native Method) 
	at java.lang.reflect.Method.invoke(Method.java:515) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610) 
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
	at dalvik.system.NativeStart.main(Native Method) 


 ```

**Comment by ThinkingMonkey** [comment]
Have currently resolved it by removing the animation for SDK< 21:
[Removed animation of arc for SDK < 21.](https://github.com/ThinkingMonkey/Spotlight/commit/f4b9ead80128e7c1230b8872588f1711caaf41e9)

Waiting for a more legit solution.

**Comment by 29jitender** [comment]
Thanks @ThinkingMonkey

Actually i forgot to add this in my Gradle file thats why we were not able to execute AnimatedVectorDrawableCompat. Read this for more info [Support Library 23.2](http://android-developers.blogspot.in/2016/02/android-support-library-232.html)

```
android {  
   defaultConfig {  
     vectorDrawables.useSupportLibrary = true  
    }  
 }  

```
