### ISSUE TITLE
IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by ZomerD** [wooplr/Spotlight#26]
Hi,

I've received this exception. Could you tell why?

Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:933)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
       at com.wooplr.spotlight.SpotlightView.onDraw(SpotlightView.java:232)
       at android.view.View.draw(View.java:16068)
       at android.widget.FrameLayout.draw(FrameLayout.java:592)
       at android.view.View.updateDisplayListIfDirty(View.java:14999)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3662)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3641)
       at android.view.View.updateDisplayListIfDirty(View.java:14959)
       at android.view.View.getDisplayList(View.java:15022)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2741)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2573)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2165)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by AndriyServatyak** [comment]
I have the same issue

**Comment by dhavalwooplr** [comment]
It seems that width or height was 0 at this line.

`bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)`

Reason can be anything, so right now just catched this exception to prevent crash.
