### ISSUE TITLE
Why Cant I use it on android 4

### ISSUE THREAD

**Issue by rasoul13** [wooplr/Spotlight#28]
I keep getting error on android 4 but I did not see anything on your doc that says this is only for android 5 or 6 
 here is the error it seems it occurs when the arc or line animation starts :

`08-30 14:46:23.248 14239-14239/ir.cafevas.ferfereh E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     android.content.res.Resources$NotFoundException: File res/drawable/ic_spotlight_arc.xml from drawable resource ID #0x7f0200e9
                                                                         at android.content.res.Resources.loadDrawable(Resources.java:1953)
                                                                         at android.content.res.Resources.getDrawable(Resources.java:660)
                                                                         at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128)
                                                                         at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45)
                                                                         at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192)
                                                                         at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:66)
                                                                         at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:71)
                                                                         at com.wooplr.spotlight.SpotlightView.addArcAnimation(SpotlightView.java:479)
                                                                         at com.wooplr.spotlight.SpotlightView.access$300(SpotlightView.java:52)
                                                                         at com.wooplr.spotlight.SpotlightView$4.onAnimationEnd(SpotlightView.java:432)
                                                                         at android.view.animation.Animation$3.run(Animation.java:374)
                                                                         at android.os.Handler.handleCallback(Handler.java:725)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                         at android.os.Looper.loop(Looper.java:137)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:511)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
                                                                         at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
                                                                         at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
                                                                         at android.content.res.Resources.loadDrawable(Resources.java:1950)
                                                                         at android.content.res.Resources.getDrawable(Resources.java:660) 
                                                                         at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128) 
                                                                         at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45) 
                                                                         at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202) 
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192) 
                                                                         at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:66) 
                                                                         at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:71) 
                                                                         at com.wooplr.spotlight.SpotlightView.addArcAnimation(SpotlightView.java:479) 
                                                                         at com.wooplr.spotlight.SpotlightView.access$300(SpotlightView.java:52) 
                                                                         at com.wooplr.spotlight.SpotlightView$4.onAnimationEnd(SpotlightView.java:432) 
                                                                         at android.view.animation.Animation$3.run(Animation.java:374) 
                                                                         at android.os.Handler.handleCallback(Handler.java:725) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                         at android.os.Looper.loop(Looper.java:137) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                         at dalvik.system.NativeStart.main(Native Method)  `

is there anyway I could work this out . your spotlight is really awesome I cant find anything like it.

thanks

**Comment by sachinjnd** [comment]
You can use it on Android 4 too. You need to add the following in your app's gradle file:

    defaultConfig {
        generatedDensities = []
    }
    aaptOptions {
        additionalParameters "--no-version-vectors"
    }
